/**
 * Platforma Shqiptare — të gjitha tekstet e ndërfaqes në një vend (shqip).
 * Ndrysho fjalët këtu për t'i pasqyruar kudo në aplikacion.
 */
export const t = {
  site: {
    name: "Platforma Shqiptare",
    tagline: "Të ndërtojmë të ardhmen së bashku",
    tempName: "",
    footerNote: "Nismë e pavarur qytetare",
  },

  nav: {
    home: "Ballina",
    ideas: "Idetë",
    experts: "Ekspertët",
    about: "Rreth nesh",
    admin: "Administrimi",
    account: "Llogaria ime",
    signIn: "Hyr",
    signOut: "Dil",
    newIdea: "Propozo një ide",
    newExpert: "Propozo një ekspert/e",
    menu: "Menyja",
  },

  home: {
    heroTitle: "Të ndërtojmë të ardhmen së bashku",
    heroSub:
      "Platforma Shqiptare është një nismë e pavarur qytetare ku qytetarët propozojnë dhe vetëpropozohen si ekspertë të fushave të ndryshme, diskutojnë për ide e zgjidhje për problemet e vendit. Shqipëria i ka ekspertët, brenda dhe jashtë Shqipërisë. Shqiptarët i kanë idetë, i kanë edhe zgjidhjet! Le t'i bëjmë bashkë!",
    heroTagline: "Vetëpropozohu ose propozo ekspertë. Diskuto ide. Ndërto zgjidhje për Shqipërinë që meritojmë të gjithë!",
    heroCtaPrimary: "Propozo një ide",
    heroCtaSecondary: "Propozo një ekspert/e",
    statIdeas: "Ide të propozuara",
    statExperts: "Ekspertë",
    statFields: "Fusha tematike",
    howTitle: "Propozo idenë dhe zgjidhjen tënde",
    how: [
      {
        title: "Propozo një ide",
        body: "Përshkruaj problemin dhe zgjidhjen që propozon, zgjedh një fushë dhe, nëse do, ngarko dokumente mbështetëse.",
      },
      {
        title: "Komuniteti mbështet e diskuton",
        body: "Qytetarët e tjerë e mbështesin idenë, komentojnë pro, kundër ose neutral dhe mund të propozojnë zgjidhje.",
      },
      {
        title: "Ekspertët ndërlidhen",
        body: "Ekspertë të fushës propozohen ose vetëpropozohen për idenë. Kontakti vijon jashtë platformës.",
      },
    ],
    fieldsTitle: "14 fushat",
    fieldsSub: "Çdo propozim i përket një fushe. Kliko një fushë për të parë ekspertët dhe idetë në lidhje me të.",
    mostSupported: "Idetë më të mbështetura",
    viewAll: "Shiko të gjitha",
    expertsTeaser: "Ekspertët",
    expertsTeaserSub:
      "Njerëz që ofrojnë njohuri për fushat e tyre. Vetëpropozohu ose propozo dikë që është ekspert/e dhe mund të japë një kontribut për mirëqeverisjen e Shqipërisë!",
    aboutTeaser: "Rreth nesh",
    aboutTeaserSub:
      "Një nismë e pavarur qytetare. Lexo misionin dhe rregullat tona.",
    whyTitle: "Pse Platforma Shqiptare?",
    why: [
      "Kjo platformë bazohet në një bindje të thjeshtë: Shqipërisë nuk i mungojnë njerëzit e aftë, por mekanizmat që i bëjnë ata të dukshëm, i lidhin me njëri-tjetrin dhe u japin mundësinë të kontribuojnë për të mirën publike. Akademikë, studiues, profesionistë, sipërmarrës, inxhinierë, mjekë, juristë, ekonomistë, pedagogë, artistë, ekspertë të teknologjisë dhe shumë të tjerë përbëjnë një kapital të jashtëzakonshëm njerëzor që meriton të dëgjohet dhe të angazhohet.",
      "E lidhur me aktualitetin politik të vendit, kjo platformë do të shërbejë edhe si një bazë e rëndësishme e identifikimit të ekspertëve dhe kontribuesve për një qeveri teknike apolitike.",
      "Përmes Platformës Shqiptare, çdo qytetar mund të propozojë ekspertë që i vlerëson për integritetin, profesionalizmin dhe kontributin e tyre, si edhe të paraqesë problematika, ide dhe zgjidhje për çështje që ndikojnë në zhvillimin e vendit. Këto ide diskutohen dhe pasurohen me kontributin e ekspertëve, duke nxitur dialog, bashkëpunim dhe zgjidhje të bazuara në njohuri, përvojë dhe evidencë.",
      "Nëse njeh një ekspert ose eksperte nga Shqipëria apo diaspora që mund të japë një kontribut të vlefshëm për një qeverisje më të mirë, politika publike më efektive dhe zhvillimin e vendit, propozoje në Platformën Shqiptare. Ne do ta kontaktojmë dhe do ta ftojmë të bëhet pjesë e këtij rrjeti kombëtar të ekspertizës.",
    ],
    whyMore: "Lexo më shumë",
    whyLess: "Lexo më pak",
  },

  ideas: {
    listTitle: "Idetë",
    listSub: "Ide e zgjidhje për problemet e vendit.",
    searchPlaceholder: "Kërko sipas titullit, përmbledhjes ose autorit…",
    filterTitle: "Fushat",
    filterButton: "Filtro sipas fushës",
    filterAll: "Të gjitha",
    sortNote: "Renditur sipas mbështetjes — të arkivuarat në fund.",
    empty: "Nuk u gjet asnjë ide. Provo një filtër tjetër ose propozo një ide të re.",
    supports: "mbështetje",
    comments: "komente",
    by: "nga",
    statusActive: "AKTIVE",
    statusArchived: "ARKIVUAR",
    archivedNote: "Kjo ide është arkivuar — një ekspert e mori përsipër. Vetëm për lexim.",
  },

  idea: {
    support: "Mbështet",
    supported: "E mbështetur",
    supportLogin: "Hyr për të mbështetur",
    report: "Raporto",
    archive: "Arkivo idenë",
    archiveConfirm:
      "Arkivimi do të thotë që një ekspert e mori përsipër idenë. Pas arkivimit nuk pranohen mbështetje ose komente të reja. Vazhdo?",
    proposeExpert: "Propozo një ekspert/e",
    expertsInField: "Ekspertë në këtë fushë",
    noExpertsInField: "Ende s'ka ekspertë të konfirmuar në këtë fushë.",
    linkedExperts: "Ekspertët e propozuar",
    linkApproved: "E miratuar",
    awaitingResponse: "Në pritje të përgjigjes nga",
    pendingExpert: "një ekspert i propozuar",
    contactLabel: "Kontakti",
    confirmTakeover: "Konfirmo marrjen përsipër",
    takenOver: "Marrë përsipër · arkivuar",
    documents: "Dokumente mbështetëse",
    download: "Shkarko",
    commentsTitle: "Komentet",
    addComment: "Shto një koment",
    commentLogin: "Hyr për të komentuar",
    deleteComment: "Fshi",
    deleteCommentConfirm: "Fshi këtë koment? Ky veprim s'kthehet mbrapsht.",
    proposesSolution: "Propozon një zgjidhje",
    field: "Fusha",
    subfield: "Nënfusha",
    author: "Autori",
    backToList: "← Të gjitha idetë",
  },

  stance: {
    PRO: "Pro",
    KUNDER: "Kundër",
    NEUTRAL: "Neutral",
    label: "Qëndrimi",
  },

  experts: {
    title: "Ekspertët",
    sub: "Njerëz që ofrojnë njohuri për fushat ku ndërtojmë zgjidhje.",
    filterAll: "Të gjitha fushat",
    selfNominate: "Vetëpropozohu si ekspert",
    badgePrefix: "Ekspert ·",
    privateNote: "Kontakti & CV-ja janë private (vetëm administrata).",
    empty: "Ende s'ka ekspertë në këtë fushë.",
    confirmTitle: "Konfirmo propozimin si ekspert",
    confirmAccept: "Prano",
    confirmReject: "Refuzo",
    confirmIntro:
      "Je propozuar si ekspert në Platformën Shqiptare. Nëse pranon, profili yt (emri, fusha dhe biografia) shqyrtohet nga administrata para se të publikohet. Kontakti dhe CV-ja mbeten private (vetëm administratorët e faqes).",
    confirmAccepted: "Faleminderit! Pëlqimi yt u regjistrua. Profili do të publikohet pas shqyrtimit nga administrata.",
    confirmRejected: "Propozimi u refuzua. Të dhënat e tua nuk do të publikohen.",
    confirmInvalid: "Kjo lidhje konfirmimi është e pavlefshme ose ka skaduar.",
    confirmAlready: "Ky propozim është trajtuar tashmë.",
    confirmCvNote:
      "Nëse nuk e ke ngarkuar ende, ngarko CV-në (PDF) — është e detyrueshme para se profili të publikohet.",
    engagedIdeas: "Idetë ku është angazhuar",
    noEngagedIdeas: "Ende s'ka ide të lidhura.",
    linkConfirmTitle: "Konfirmo propozimin për idenë",
    linkIntro:
      "Je propozuar si ekspert për një ide. Duke pranuar, kontakti yt i jepet autorit të idesë dhe ti merr kontaktin e tij, që të bisedoni jashtë platformës.",
    linkAccepted: "Faleminderit! Pranove propozimin dhe kontaktet u shkëmbyen.",
    linkRejected: "E refuzove propozimin për këtë ide.",
  },

  forms: {
    // Idea
    ideaTitle: "Titulli",
    ideaTitlePh: "P.sh. Dixhitalizimi i lejeve të ndërtimit",
    ideaSummary: "Përmbledhja (problemi + zgjidhja e propozuar)",
    ideaSummaryPh: "Përshkruaj problemin dhe zgjidhjen që propozon…",
    ideaField: "Fusha",
    ideaSubfield: "Nënfusha (opsionale)",
    ideaOther: "Shpjego fushën",
    ideaOtherPh: "Përshkruaj shkurt fushën që ke parasysh…",
    ideaDocs: "Dokumente mbështetëse (PDF, opsionale, publike)",
    ideaSubmit: "Publiko idenë",
    chooseField: "Zgjidh një fushë",
    chooseSubfield: "Zgjidh një nënfushë",

    // Comment
    commentBody: "Komenti yt",
    commentBodyPh: "Shkruaj mendimin tënd…",
    commentStance: "Qëndrimi",
    commentIsSolution: "Po propozoj një zgjidhje",
    commentSubmit: "Dërgo komentin",

    // Self-nominate expert
    expName: "Emër Mbiemër",
    expField: "Fusha",
    expBio: "Biografia (publike)",
    expBioPh: "Përvoja dhe njohuritë e tua në fushë…",
    expReason: "Arsyeja / motivimi (private)",
    expReasonPh: "Pse dëshiron të kontribuosh…",
    expContact: "Kontakti (privat)",
    expContactPh: "Email ose telefon — vetëm administratorët e faqes e shohin",
    expCv: "CV (PDF, opsionale, private)",
    selfNominateSubmit: "Dërgo vetëpropozimin",

    // Nominate from idea
    nomFieldPrefilled: "Fusha (e idesë)",
    nomName: "Emër Mbiemër i propozuar",
    nomBio: "Biografia (bëhet publike nëse konfirmohet)",
    nomReason: "Arsyeja",
    nomContact: "Kontakti i propozuar (privat)",
    nomProposerName: "Emri yt (propozuesi)",
    nomProposerContact: "Kontakti yt (privat)",
    nomCv: "CV e propozuar (PDF, opsionale, private)",
    nominateSubmit: "Dërgo propozimin",
    nominateNote:
      "Profili nuk shfaqet publikisht menjëherë — shqyrtohet nga administrata para se të publikohet.",

    // Experts v2
    expAreas: "Fushat (1–3)",
    expCvRequired: "CV (PDF, e detyrueshme)",
    expCvReplace: "Zëvendëso CV-në (PDF, opsionale)",
    areasHint: "fusha të zgjedhura (maks. 3)",
    selfRegisterNote:
      "Profili yt shqyrtohet nga administrata para se të publikohet. Kontakti dhe CV-ja mbeten private (vetëm administratorët e faqes).",
    typeaheadHint: "Kërko një ekspert ekzistues me emër, ose propozo një person të ri.",
    searchExpertPh: "Kërko me emër…",
    noExpertFound: "Nuk u gjet asnjë ekspert. Propozo një person të ri.",
    proposeNewPerson: "Propozo një person të ri",
    backToSearch: "Kthehu te kërkimi",
    nomContactHint: "Vetëm administratorët e faqes e shohin — për ta kontaktuar jashtë platformës.",

    // Report
    reportReason: "Arsyeja e raportimit",
    reportReasonPh: "Pse po e raporton këtë përmbajtje…",
    reportSubmit: "Dërgo raportimin",

    // Auth
    authEmail: "Email",
    authName: "Emër Mbiemër",
    authNamePh: "Emri yt i plotë",
    authSignIn: "Më dërgo lidhjen e hyrjes",
    authNote:
      "Të dërgojmë një lidhje hyrjeje me email. S'ka fjalëkalim. Një llogari për person.",
    required: "E detyrueshme",
  },

  account: {
    title: "Llogaria ime",
    yourIdeas: "Idetë e mia",
    noIdeas: "Ende s'ke propozuar asnjë ide.",
    expertProfile: "Profili im si ekspert",
    linksAwaitingYou: "Ide që presin përgjigjen tënde",
    linkConsentNote: "Duke pranuar, kontakti yt i jepet autorit të idesë dhe ti merr kontaktin e tij.",
    approvedLinks: "Idetë e pranuara",
    awaitingAuthorConfirm: "Në pritje të konfirmimit të autorit",
    takeOver: "Po e marr përsipër",
    editProfile: "Profili & të dhënat",
    claimTitle: "Profile për t'u pretenduar",
    claimBtn: "Pretendo profilin",
    deleteTitle: "Fshi llogarinë",
    deleteWarn:
      "Fshirja e llogarisë heq përfundimisht të dhënat e tua personale, idetë, komentet dhe mbështetjet. Ky veprim s'kthehet mbrapsht.",
    deleteBtn: "Fshi llogarinë time",
    deleteConfirm: "A je i/e sigurt? Ky veprim s'kthehet mbrapsht.",
  },

  admin: {
    title: "Administrimi",
    tabReports: "Raportime",
    tabIdeas: "Idetë",
    tabAccounts: "Llogaritë",
    tabExperts: "Ekspertët",
    tabEdits: "Ndryshime",
    tabMerge: "Bashko dublikatët",
    reportPost: "Postimi",
    reportReason: "Arsyeja",
    reportReporter: "Raportuesi",
    reportResolve: "Zgjidh",
    reportDelete: "Fshi postimin",
    reportDeleteComment: "Fshi komentin",
    resolved: "Zgjidhur",
    delete: "Fshi",
    ban: "Pezullo llogarinë",
    unban: "Riaktivizo",
    approve: "Mirato",
    reject: "Refuzo",
    viewPrivate: "Të dhëna private",
    downloadCv: "Shkarko CV",
    pending: "Në pritje",
    confirmed: "Të konfirmuar",
    noPrivate: "—",
    proposer: "Propozuesi",
    contact: "Kontakti",
    reason: "Arsyeja",
    mergeTitle: "Bashko dublikatët",
    mergeNote: "Zgjidh profilin që mbetet dhe atë që bashkohet në të (lidhjet lëvizin, fushat kufizohen në 3).",
    mergeKeep: "Profili që mbetet",
    mergeDrop: "Profili që bashkohet (fshihet)",
    mergeBtn: "Bashko",
    mergeConfirm: "Bashko këto dy profile? Ky veprim s'kthehet mbrapsht.",
  },

  notifications: {
    title: "Njoftimet",
    empty: "S'ke njoftime.",
    markAllRead: "Shëno të gjitha si të lexuara",
    bellLabel: "Njoftimet",
  },

  auth: {
    checkEmail: "Kontrollo email-in tënd",
    checkEmailBody:
      "Të dërguam një lidhje hyrjeje. Hape email-in dhe kliko lidhjen për të vazhduar.",
    verifying: "Po verifikohet…",
    error: "Diçka shkoi keq",
    errorBody: "Lidhja mund të ketë skaduar ose është përdorur tashmë. Provo përsëri.",
    banned: "Kjo llogari është pezulluar.",
    errorVerification:
      "Lidhja e hyrjes ka skaduar ose është përdorur tashmë. Kërko një lidhje të re më poshtë.",
    errorGeneric: "Hyrja dështoi. Provo përsëri më poshtë.",
    alreadyIn: "Je tashmë i kyçur",
    alreadyInBody: "Je i kyçur si",
    goAccount: "Shko te llogaria",
  },

  common: {
    save: "Ruaj",
    edit: "Ndrysho",
    cancel: "Anulo",
    submit: "Dërgo",
    close: "Mbyll",
    loading: "Po ngarkohet…",
    error: "Ndodhi një gabim.",
    success: "U krye me sukses.",
    requiredField: "Kjo fushë është e detyrueshme.",
    loginRequired: "Duhet të hysh për të vazhduar.",
    notFoundTitle: "Faqja nuk u gjet",
    notFoundBody: "Faqja që kërkove nuk ekziston ose është hequr.",
    errorTitle: "Ndodhi një gabim",
    errorBody: "Na vjen keq — diçka shkoi keq. Provo përsëri.",
    backHome: "Kthehu në ballinë",
    retry: "Provo përsëri",
  },

  toast: {
    ideaCreated: "Ideja u publikua.",
    supported: "E mbështete idenë.",
    unsupported: "Hoqe mbështetjen.",
    commented: "Komenti u shtua.",
    commentDeleted: "Komenti u fshi.",
    archived: "Ideja u arkivua.",
    reported: "Faleminderit — raportimi u dërgua.",
    expertSelf: "Vetëpropozimi u dërgua. Do të shqyrtohet nga administrata para se të publikohet.",
    expertNominated: "Propozimi u dërgua. Do të shqyrtohet nga administrata para se të publikohet.",
    profileSaved: "Profili u ruajt.",
    profileClaimed: "Profili u pretendua.",
    linkAccepted: "Pranove propozimin.",
    linkRejected: "Refuzove propozimin.",
    takeoverMarked: "Njoftove autorin — pret konfirmimin.",
    takeoverConfirmed: "Konfirmove; ideja u arkivua.",
    accountDeleted: "Llogaria u fshi.",
    fileTooBig: "Skedari është shumë i madh (maks. 10 MB).",
    fileNotPdf: "Lejohen vetëm skedarë PDF.",
    rateLimited: "Shumë veprime në pak kohë. Provo pas pak.",
    turnstileFailed: "Verifikimi kundër robotëve dështoi. Provo përsëri.",
  },

  about: {
    title: "Rreth Platformës Shqiptare",
    missionTitle: "Misioni",
    mission: [
      "Platforma Shqiptare është një nismë e pavarur qytetare që synon të krijojë një rrjet të gjerë ekspertësh, akademikësh dhe profesionistësh nga fusha të ndryshme, duke e vendosur ekspertizën në shërbim të zhvillimit të vendit. Platforma është një nismë që synon të identifikojë dhe të bëjë bashkë ekspertë, profesionistë dhe qytetarë të angazhuar për të ndërtuar zgjidhje konkrete për sfidat e Shqipërisë.",
      "Në këtë platformë, qytetarët mund të propozojnë ekspertë nga fusha të ndryshme, të ndajnë ide, të diskutojnë problematika dhe të kontribuojnë me zgjidhje për çështje me interes publik. Besojmë se Shqipëria ka një potencial të jashtëzakonshëm njerëzor, si brenda vendit ashtu edhe në diasporë, i cili shpesh mbetet i pashfrytëzuar.",
      "Shpesh dëgjojmë të thuhet se Shqipërisë i mungojnë ekspertët për të ndërtuar politika më të mira dhe për të garantuar një qeverisje më cilësore. Ne besojmë të kundërtën. Shqipëria ka shumë profesionistë me integritet, përvojë dhe vizion, të cilët mund të japin një kontribut të vyer në hartimin e politikave publike, zhvillimin ekonomik, arsimin, shëndetësinë, drejtësinë, teknologjinë, mjedisin dhe çdo fushë tjetër të rëndësishme për të ardhmen e vendit.",
      "Platforma synon të ndërtojë ura bashkëpunimi ndërmjet ekspertizës shqiptare në çdo vend të botës dhe angazhimit qytetar, duke promovuar kulturën e dialogut, inovacionit dhe pjesëmarrjes aktive në proceset e zhvillimit dhe vendimmarrjes, dhe duke promovuar këtë metodë të mirëqeverisjes si model! Besojmë se zgjidhjet më të mira lindin kur ekspertët dhe qytetarët punojnë së bashku, ndajnë njohuritë dhe kontribuojnë në mënyrë të hapur për të mirën e përbashkët.",
      "Nëse njeh një ekspert ose eksperte nga Shqipëria apo diaspora që mendon se mund të kontribuojë me njohuritë dhe përvojën e tij ose të saj për një qeverisje më të mirë dhe për zhvillimin e vendit, propozoje në këtë platformë. Ne do ta kontaktojmë për ta ftuar të bëhet pjesë e këtij rrjeti të ekspertizës dhe të kontribuojë në ndërtimin e ideve dhe zgjidhjeve që i shërbejnë interesit publik.",
      "Kjo platformë e nisur nga ekspertë të pavarur të mirëqeverisjes, në Shqipëri dhe në diasporë, nuk është një parti politike dhe nuk përfaqëson asnjë institucion. Platforma Shqiptare është një hapësirë e pavarur, gjithëpërfshirëse dhe e hapur për çdo ekspert dhe qytetar që dëshiron të kontribuojë me njohuritë, përvojën dhe idetë e tij për ndërtimin e një Shqipërie më të zhvilluar, më demokratike dhe më të drejtë.",
      "Shqipëria ka ekspertët që i duhen, ka idetë, ka edhe zgjidhjet! Le t'i bëjmë bashkë dhe t'u japim mundësinë të kontribuojnë për Shqipërinë që të gjithë meritojmë.",
    ],
    principlesTitle: "Parimet",
    principlesIntro:
      "Kjo platformë u jep qytetarëve mundësinë të identifikojnë, po aq sa ekspertët, edhe problematikat që hasin në komunitetet e tyre, të propozojnë ide dhe zgjidhje konkrete, si dhe të marrin pjesë në diskutime të hapura mbi çështje me interes publik. Çdo propozim mund të pasurohet përmes kontributit të ekspertëve, duke krijuar një dialog konstruktiv ndërmjet qytetarëve dhe profesionistëve dhe duke nxitur zhvillimin e zgjidhjeve të bazuara në evidencë, përvojë dhe praktika të mira, ashtu siç duhet të jetë një qeverisje e mirë, duke funksionuar si një platformë:",
    principles: [
      "E pavarur dhe jopartiake.",
      "E hapur — leximi i lirë për të gjithë, pa llogari.",
      "Me përgjegjësi — çdo ide dhe propozim nënshkruhet me emrin e vërtetë.",
      "Me cilësi — ekspertët ndihmojnë që idetë të bëhen të zbatueshme.",
      "Me respekt — diskutim civil, pa fyerje dhe pa gjuhë urrejtjeje.",
    ],
    rulesTitle: "Rregullat e komunitetit",
    rules: [
      "Përdorimi i emrit të vërtetë. Një llogari për person.",
      "Ndalimi i gjuhës së urrejtjes, fyerjeve, shpifjeve apo përmbajtjeve të paligjshme.",
      "Ndalimi i publikimit të të dhënave personale të të tjerëve pa pëlqim.",
      "Respektimi i qëndrimeve të ndryshme.",
    ],
    penaltyTitle: "Pasojat",
    penalty:
      "Shkelja e rregullave çon në heqjen e llogarisë. Administrata mund të fshijë ide, komente dhe llogari që shkelin këto rregulla.",
  },
} as const;

export type Strings = typeof t;
